In [13]:
import pandas as pd

# read file into pandas using a relative path
path = "D:\ML Internship\sms.tsv"
sms = pd.read_table(path, header=None, names=['label', 'message'])

In [14]:
sms.shape

(5572, 2)

In [15]:
sms.head(10)

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [16]:
# examine the class distribution
sms.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [17]:
# convert label to a numerical variable because some classification algorithms want their classes to be of numeric values as well.
sms['label'] = sms.label.map({'ham':0, 'spam':1})

In [18]:
# check that the conversion worked
sms.head(10)

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...
5      1  FreeMsg Hey there darling it's been 3 week's n...
6      0  Even my brother is not like to speak with me. ...
7      0  As per your request 'Melle Melle (Oru Minnamin...
8      1  WINNER!! As a valued network customer you have...
9      1  Had your mobile 11 months or more? U R entitle...

In [29]:
#Some preprocessing needs to be done before we start extracting features.

# Making everything lower case 
sms['message'] = sms['message'].apply(lambda x: " ".join(x.lower() for x in x.split()))

In [30]:
sms.head()

   label                                            message
0      0  go until jurong point, crazy.. available only ...
1      0                      ok lar... joking wif u oni...
2      1  free entry in 2 a wkly comp to win fa cup fina...
3      0  u dun say so early hor... u c already then say...
4      0  nah i don't think he goes to usf, he lives aro...

In [31]:
# Removing Punctuation

sms['message'] = sms['message'].str.replace('[^\w\s]','')
sms['message'].head()

0    go until jurong point crazy available only in ...
1                              ok lar joking wif u oni
2    free entry in 2 a wkly comp to win fa cup fina...
3          u dun say so early hor u c already then say
4    nah i dont think he goes to usf he lives aroun...
Name: message, dtype: object

In [33]:
# Removal of Stop Words

stop = set([
    "a", "about", "above", "across", "after", "afterwards", "again", "against",
    "all", "almost", "alone", "along", "already", "also", "although", "always",
    "am", "among", "amongst", "amoungst", "amount", "an", "and", "another",
    "any", "anyhow", "anyone", "anything", "anyway", "anywhere", "are",
    "around", "as", "at", "back", "be", "became", "because", "become",
    "becomes", "becoming", "been", "before", "beforehand", "behind", "being",
    "below", "beside", "besides", "between", "beyond", "bill", "both",
    "bottom", "but", "by", "call", "can", "cannot", "cant", "co", "con",
    "could", "couldnt", "cry", "de", "describe", "detail", "do", "done",
    "down", "due", "during", "each", "eg", "eight", "either", "eleven", "else",
    "elsewhere", "empty", "enough", "etc", "even", "ever", "every", "everyone",
    "everything", "everywhere", "except", "few", "fifteen", "fify", "fill",
    "find", "fire", "first", "five", "for", "former", "formerly", "forty",
    "found", "four", "from", "front", "full", "further", "get", "give", "go",
    "had", "has", "hasnt", "have", "he", "hence", "her", "here", "hereafter",
    "hereby", "herein", "hereupon", "hers", "herself", "him", "himself", "his",
    "how", "however", "hundred", "i", "ie", "if", "in", "inc", "indeed",
    "interest", "into", "is", "it", "its", "itself", "keep", "last", "latter",
    "latterly", "least", "less", "ltd", "made", "many", "may", "me",
    "meanwhile", "might", "mill", "mine", "more", "moreover", "most", "mostly",
    "move", "much", "must", "my", "myself", "name", "namely", "neither",
    "never", "nevertheless", "next", "nine", "no", "nobody", "none", "noone",
    "nor", "not", "nothing", "now", "nowhere", "of", "off", "often", "on",
    "once", "one", "only", "onto", "or", "other", "others", "otherwise", "our",
    "ours", "ourselves", "out", "over", "own", "part", "per", "perhaps",
    "please", "put", "rather", "re", "same", "see", "seem", "seemed",
    "seeming", "seems", "serious", "several", "she", "should", "show", "side",
    "since", "sincere", "six", "sixty", "so", "some", "somehow", "someone",
    "something", "sometime", "sometimes", "somewhere", "still", "such",
    "system", "take", "ten", "than", "that", "the", "their", "them",
    "themselves", "then", "thence", "there", "thereafter", "thereby",
    "therefore", "therein", "thereupon", "these", "they", "thick", "thin",
    "third", "this", "those", "though", "three", "through", "throughout",
    "thru", "thus", "to", "together", "too", "top", "toward", "towards",
    "twelve", "twenty", "two", "un", "under", "until", "up", "upon", "us",
    "very", "via", "was", "we", "well", "were", "what", "whatever", "when",
    "whence", "whenever", "where", "whereafter", "whereas", "whereby",
    "wherein", "whereupon", "wherever", "whether", "which", "while", "whither",
    "who", "whoever", "whole", "whom", "whose", "why", "will", "with",
    "within", "without", "would", "yet", "you", "your", "yours", "yourself",
    "yourselves"])

sms['message'] = sms['message'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
sms['message'].head()

0    jurong point crazy available bugis n great wor...
1                              ok lar joking wif u oni
2    free entry 2 wkly comp win fa cup final tkts 2...
3                          u dun say early hor u c say
4                        nah dont think goes usf lives
Name: message, dtype: object

In [38]:
# how to define X and y (from the SMS data) for use with TF-IDFVectorizer
X = sms.message
y = sms.label
print(X.shape)
print(y.shape)

(5572,)
(5572,)

In [39]:
# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4179,)
(1393,)
(4179,)
(1393,)

In [43]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=1000)
train_vect = tfidf.fit_transform(X_train)

train_vect

<4179x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 21189 stored elements in Compressed Sparse Row format>

In [47]:
print(train_vect)

  (0, 373)	0.25020960544618226
  (0, 665)	0.2695693380407228
  (0, 611)	0.26567277329291067
  (0, 483)	0.24648267528252585
  (0, 699)	0.3013485003213593
  (0, 460)	0.2604213876908336
  (0, 144)	0.2588048684308026
  (0, 634)	0.293539180057629
  (0, 317)	0.3625461439462388
  (0, 633)	0.20315310067107908
  (0, 11)	0.31090633587104227
  (0, 893)	0.2839813445079461
  (0, 818)	0.2675767612595955
  (1, 228)	1.0
  (2, 403)	0.43834297968522384
  (2, 577)	0.4093640668127523
  (2, 825)	0.3856928503254032
  (2, 796)	0.4067671147588081
  (2, 892)	0.5710149144478316
  (3, 483)	0.2622839095204448
  (3, 825)	0.20411230960428572
  (3, 796)	0.21526500995401895
  (3, 386)	0.3123570598002142
  (3, 157)	0.2598196042111001
  (3, 667)	0.2992449293468607
  :	:
  (4174, 968)	0.7771364514694908
  (4175, 643)	0.3516168032267615
  (4175, 153)	0.3772610513020591
  (4175, 597)	0.5599213515780264
  (4175, 477)	0.34308839313340744
  (4175, 225)	0.3589622780836287
  (4175, 568)	0.4170902064496864
  (4176, 574)	0.5560124956168504
  (4176, 810)	0.490187877286645
  (4176, 982)	0.45478058548161676
  (4176, 486)	0.49370088996084766
  (4177, 825)	0.2276646823975916
  (4177, 439)	0.1906834081644549
  (4177, 533)	0.27008684697363
  (4177, 563)	0.26918703903734753
  (4177, 700)	0.24215861771548208
  (4177, 853)	0.2335049453307211
  (4177, 19)	0.29853649435363977
  (4177, 59)	0.3528231853951223
  (4177, 437)	0.31532526219078255
  (4177, 750)	0.3250380941608316
  (4177, 9)	0.34433051970462925
  (4177, 214)	0.34056303186516135
  (4178, 157)	0.7054547105556949
  (4178, 774)	0.7087550009381105

In [48]:
test_vect = tfidf.fit_transform(X_test)

test_vect

<1393x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 7525 stored elements in Compressed Sparse Row format>

In [49]:
print(test_vect)

  (0, 678)	1.0
  (1, 991)	0.39243275625415797
  (1, 681)	0.4796340307539851
  (1, 348)	0.3612353857446583
  (1, 501)	0.4051597970741605
  (1, 546)	0.5668353052538123
  (3, 375)	1.0
  (4, 317)	0.27284344432422053
  (4, 69)	0.23910483730031493
  (4, 797)	0.5823024247271341
  (4, 854)	0.2841909219885142
  (4, 138)	0.2841909219885142
  (4, 205)	0.2249424107031195
  (4, 677)	0.3094589804029136
  (4, 453)	0.2781616442202074
  (4, 932)	0.20017328014646027
  (4, 774)	0.32244854854627325
  (5, 614)	0.33663743673746244
  (5, 860)	0.48187871585210523
  (5, 352)	0.36238368597491805
  (5, 930)	0.4527143672875936
  (5, 174)	0.359099664828686
  (5, 936)	0.43502107524361167
  (6, 932)	0.4657330018134129
  (6, 892)	0.6965603537726783
  :	:
  (1390, 604)	0.11115140797720427
  (1390, 847)	0.10358366160023497
  (1390, 853)	0.11707060859101708
  (1390, 747)	0.1212873227046971
  (1390, 329)	0.15851023632934425
  (1390, 484)	0.13731835902602335
  (1390, 542)	0.9510614179760655
  (1391, 548)	0.23424960530706104
  (1391, 907)	0.19987541493354835
  (1391, 956)	0.2674156379187922
  (1391, 922)	0.3318972473542446
  (1391, 421)	0.3318972473542446
  (1391, 965)	0.2699269416445429
  (1391, 805)	0.26502118218012755
  (1391, 560)	0.3170898148998059
  (1391, 957)	0.3318972473542446
  (1391, 290)	0.35276715123728775
  (1391, 284)	0.36757458369172646
  (1392, 930)	0.2965111307574795
  (1392, 520)	0.5698453605377888
  (1392, 252)	0.29983585955223446
  (1392, 361)	0.33784890311708804
  (1392, 51)	0.3313895366345036
  (1392, 719)	0.363624479986238
  (1392, 571)	0.37586194668194156

In [50]:
# Now we have processed the text to make it useful for running further classification or Regression algorithms

# import and instantiate a Multinomial Naive Bayes model
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [54]:
# train the model using train_vect (timing it with an IPython "magic command")
%time nb.fit(train_vect, y_train)

Wall time: 3.97 ms

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [55]:
# make class predictions for test_vect
y_pred_class = nb.predict(test_vect)

In [56]:
# calculate accuracy of class predictions
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.8657573582196698

In [57]:
# print the confusion matrix
metrics.confusion_matrix(y_test, y_pred_class)

array([[1127,   81],
       [ 106,   79]], dtype=int64)

In [58]:
# print message text for the false positives (ham incorrectly classified as spam)
X_test[(y_pred_class==1) & (y_test==0)]
#or more elegant way is to use X_test[y_pred_class > y_test]

4674    forgot 2 ask ü smth theres card da present lei...
3224                                           pain catch
3214                                         whats ur pin
1272    havent collected dough pls let know place sent...
3242           ok ive sent u da latest version da project
2849    sad story man week bday wife didnt wish parent...
2262                           did wot did say u c 4 dust
407     slightly disastrous class pm fav darlings hope...
1074    lul im gettin juicy gossip hospital nurses tal...
4804                                          plan manage
2198                                            bring got
4950                                      bus way calicut
4201                                     come tomorrow di
1016    dearregret cudnt pick calldrove frm ctla cochi...
5490                                               k sent
996                                    change e escalator
4419                                                 free
4511                       weekend fine excuse decorating
2706             mean come chase stated watch movies want
5301                                   time come tomorrow
2319                                        way office da
2600                          gosh pain spose better come
3232                                      plm come da way
2617                                      went ur hon lab
554     ok night warm bath drink cup milk youll work m...
2839                            trying chinese food place
3354                            emailed yifeng oredi ü fr
5338                                            wanna gym
4923    hi dear urgnt dont know whats problem dont wan...
3745                   names penis girls story doesnt add
                              ...
1764             joys father john john joys father mandan
3589           wereare free nalla adi entey nattil kittum
552                     hurry ive weeddeficient like days
4699                                     don dawhats plan
1162                                               k sent
1620                               friends u stay fb chat
205                                         u alter 11 ok
5361                           yep program youre slacking
3816    chikkuk wat abt tht guy did stopped irritating...
2076           come later normally bathe da afternoon mah
2320                                        place want da
1554                                   ok dear did chechi
232                               dear going rubber place
5104    boy loved gal propsd bt didnt mind gv lv lttrs...
4745                                         thinking u x
4733                       wat time r ü going xins hostel
827                                  hahahause brain dear
1685                                 want bold 2 bb torch
197                               did u got persons story
1586    wondering okay uncle john let know things nige...
99                                   cup coffee animation
3794                                   hey angry reply dr
2905    hi darlin hope nice night wish come wait love ...
5428                               didnt complete gist oh
3357    ok problem taxi c ing tomorrow tuesday tuesday...
4709                 did say bold torch later torch 2bold
2594                    tmr timin da wat cos got lesson 6
1010    dear heroi leaving qatar tonite apt opportunit...
1988                            callsmessagesmissed calls
932     congratulations ore mo owo wa enjoy wish happy...
Name: message, Length: 81, dtype: object

In [59]:
# print message text for the false negatives (spam incorrectly classified as ham)
X_test[(y_pred_class==0) & (y_test==1)]
#or more elegant way is to use 
#X_test[y_pred_class < y_test]

147     freemsg havent replied text im randy sexy fema...
4517    congrats 2 mobile 3g videophones r 09061744553...
3316    free message activate 500 free text messages r...
1745    conacted dating service entered phone fancy yo...
1064    new local dates area lots new people registere...
1687    todays vodafone numbers ending 0089my digits s...
3642    stop club tones replying stop mix mytonecomenj...
4460    welcome ukmobiledate msg free giving free call...
2680    new tones week include 1mcflyall ab 2 sara jor...
1217                          1 new voicemail 08719181513
3766    u know asked dating service 2 contact guess 09...
763     urgent ur 500 guaranteed award unclaimed 09066...
3780    claim 200 shopping spree just 08717895698 won ...
881     reminder downloaded content paid goto httpdoit...
4376    ur tonexs subscription renewed charged 450 cho...
3132    lookatme thanks purchase video clip lookatme y...
3819    74355 xmas iscoming ur awarded 500 cd gift vou...
2954    urgent mobile awarded 1500 bonus caller prize ...
2295                            1 new message 08718738034
4272    natalja 25f inviting friend reply yes440 no440...
420     send logo 2 ur lover 2 names joined heart txt ...
2209    urgent 4 costa del sol holiday 5000 await coll...
5269    dont prize customer tc wwwtcbiz 18 150pmin pol...
1380    1 nokia tone 4 ur mob week just txt nok 87021 ...
2514    u won nokia 6230 plus free digital camera u u ...
67      urgent ur awarded complimentary trip eurodisin...
5110                            1 new message 08715205273
1045    know know fancies 09058097218 pobox 6 ls15hb 150p
4258    important information 4 orange user today luck...
4965    dear voucher holder meal use following link pc...
                              ...
159     customer service annoncement new years deliver...
2941                            1 new message 08712400200
4673    customer service announcement recently tried m...
2581    u subscribed best mobile content service uk 3 ...
4834    new mobiles 2004 txt nokia 89545 collect today...
5365    camera awarded sipix digital camera 0906122106...
1625    500 free text msgs just text ok 80488 credit a...
4845    won valued vodafone customer computer picked w...
3564    auction round 4 highest bid 54 maximum bid 71 ...
3998    bored housewives chat n date 08717507711 btnat...
823     smsservices yourinclusive text credits pls got...
2863                       adult 18 content video shortly
1126    taking mobile survey yesterday 500 texts 2 use...
4701    win winner mr t foley won ipod exciting prizes...
1718    wow boys r 2007 uk tour win vip tickets preboo...
5487    2p min germany 08448350055 bt line just 2p min...
5037    wont believe true incredible txts reply g lear...
5141    free 1st week no1 nokia tone 4 ur mobile week ...
4299    4 costa del sol holiday 5000 await collection ...
1963    80488 500 free text messages valid 31 december...
191                unique 30th august wwwareyouuniquecouk
2247    hi ya babe x u 4goten bout scammers getting sm...
273     hmv bonus special 500 pounds genuine hmv vouch...
4514                      money won wining number 946 wot
789     5 free polyphonic tones 087018728737 national ...
4377    dont prize customer tc wwwtcbiz 18 150pmin pol...
5178    sms auction brand new nokia 7250 4 auction tod...
1961    guess somebody know secretly fancies wanna 090...
1714    hard live 121 chat just 60pmin choose girl con...
1793    win winner mr t foley won ipod exciting prizes...
Name: message, Length: 106, dtype: object

In [61]:
# Comparing models
#We will compare multinomial Naive Bayes with logistic regression:

# import and instantiate a logistic regression model
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [62]:
# train the model using X_train_dtm
%time logreg.fit(train_vect, y_train)

Wall time: 976 ms

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [63]:
# make class predictions for X_test_dtm
y_pred_class = logreg.predict(test_vect)

In [64]:
# calculate accuracy
metrics.accuracy_score(y_test, y_pred_class)

0.8700646087580761

In [65]:
# Examining a model for further insight
#We will examine the our trained Naive Bayes model to calculate the approximate "spamminess" of each token.

In [66]:
# store the vocabulary of X_train
X_train_tokens = tfidf.get_feature_names()
len(X_train_tokens)

1000

In [67]:
# examine the first 50 tokens
print(X_train_tokens[0:50])

['020603', '0800', '08000839402', '08000930705', '08718720201', '09050090044', '10', '100', '1000', '11', '150', '150p', '150pmin', '150pmsg', '150ppm', '16', '18', '1st', '200', '2000', '2004', '250', '2nd', '300', '350', '50', '500', '5000', '530', '750', '83600', '85023', '86688', '87066', '87077', '87575', '9ja', 'abi', 'abiola', 'able', 'abt', 'access', 'account', 'actually', 'ad', 'add', 'address', 'affection', 'aft', 'afternoon']

In [68]:
# examine the last 50 tokens
print(X_train_tokens[-50:])

['whats', 'whos', 'wid', 'wif', 'wife', 'wil', 'win', 'winner', 'wish', 'wishing', 'wit', 'wiv', 'wk', 'wkly', 'wnt', 'won', 'wonderful', 'wondering', 'wont', 'word', 'words', 'work', 'workin', 'working', 'world', 'worries', 'worry', 'worth', 'wot', 'wow', 'wrong', 'wun', 'xmas', 'xx', 'xxx', 'ya', 'yahoo', 'yar', 'yeah', 'year', 'years', 'yes', 'yesterday', 'yo', 'yogasana', 'youll', 'youre', 'yr', 'yun', 'yup']

In [69]:
# Naive Bayes counts the number of times each token appears in each class
nb.feature_count_

array([[ 0.        ,  0.        ,  0.        , ...,  1.28488782,
        17.13269784,  0.        ],
       [ 4.09705418,  3.01174689,  3.25113176, ...,  1.10779222,
         0.        ,  1.6755781 ]])

In [70]:
# rows represent classes, columns represent tokens
nb.feature_count_.shape

(2, 1000)

In [71]:
# number of times each token appears across all HAM messages
ham_token_count = nb.feature_count_[0, :]
ham_token_count

array([  0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   3.01694982,   0.63882256,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         1.73397805,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.61245323,   0.        ,
         3.2604561 ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   1.38325204,   3.30694568,
         2.31926667,   0.        ,   0.        ,   0.        ,
         0.        ,   0.93232535,   0.        ,   0.        ,
         1.81581153,   2.06629077,   1.74515351,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         1.29387818,   3.55126821,   7.98259779,  11.14594291,
         3.26544184,   4.80360426,   9.03084616,   7.03343885,
         0.        ,   4.98446104,   8.28276902,   1.72908164,
         3.84509478,   9.31394708,   4.82196578,  15.66930449,
         3.93649087,   3.18571706,   3.35721987,   8.73758471,
        15.85489184,   3.32043165,   1.19137586,   4.45689367,
         3.35382208,   3.00377593,   1.33096456,   3.33200469,
         0.        ,   7.67109616,   2.34210393,   1.83061489,
        24.86646532,   3.6541249 ,   9.77799642,   5.37096489,
         4.68990475,   0.28926423,   0.49557325,   4.33585348,
         2.19012817,   0.36780847,   0.        ,   0.73833708,
         0.        ,   7.20048105,   7.91588631,   2.37767395,
        20.47445133,   1.7064872 ,   9.2708841 ,   9.96890522,
         3.21857408,   3.17638321,   3.12002082,   3.87882546,
         3.56441873,   3.04174934,   3.06429354,   4.53372792,
         4.45168066,  10.6484048 ,   7.7604568 ,  10.41284985,
         9.74302121,  11.86964809,  11.96119883,  13.15361486,
         4.03491878,   0.        ,   2.15327959,   0.        ,
         4.72941055,   3.32902776,   4.92772305,   2.47757783,
         4.04232479,   1.53787992,   7.22530793,   5.79783802,
         4.82025024,  10.11729471,   7.16341133,   3.00579718,
         4.22406224,   0.        ,   2.67449871,  10.2933857 ,
         5.62008838,  16.21599843,   9.53607499,   3.54306839,
         4.16321476,   3.58315162,   0.        ,  10.81737938,
         1.09996416,  11.32358979,   2.87759529,  18.64097196,
         6.76924036,   4.32684153,   5.19520492,   6.16553216,
         4.6489892 ,   8.04894964,   2.39431813,   0.        ,
         0.        ,   4.50904606,   2.56922094,  13.94348498,
         3.97530095,   3.61770677,   6.94939739,   4.56490564,
         2.53950278,   3.76501048,   0.        ,  18.54705222,
         5.44969631,   0.29292189,   0.33388514,   1.50576621,
         0.        ,   7.77691451,   1.37189884,  64.7877559 ,
         5.21564865,   4.96176011,  17.94229509,   0.70710678,
         5.86744506,   3.52896359,   3.6096929 ,   0.        ,
         2.7905915 ,   2.91535305,   2.32245491,   0.        ,
         3.88563294,  15.74585516,   2.90122154,   4.37939569,
        16.57390076,   4.01990208,   3.98484729,   5.70194993,
         5.2726879 ,   3.41005115,   2.83627928,   1.22545378,
         0.        ,   0.        ,   0.        ,   3.57689662,
         1.04070789,   0.        ,   4.02857832,   3.66903044,
         2.05290337,  42.31899667,  10.73618529,   4.98700032,
         3.83508237,   9.17534411,   4.45159152,   0.        ,
        41.42685281,   6.09990711,   3.57710393,  30.94375933,
         3.60627456,   3.81261251,   3.35886667,   0.42585187,
         0.28775327,   7.85588576,   3.79456538,   7.72251355,
        33.75468739,  22.82176441,   4.1384336 ,   2.19310077,
         3.25868519,   5.44544563,   0.        ,   4.45889663,
        13.21375704,   0.28610266,   9.57833705,   1.47316453,
         3.10771244,   4.83130838,  11.57118658,   7.59653396,
         0.        ,   3.29569515,  27.18620193,   5.07332561,
        61.27844376,   2.39916792,   3.89148001,   2.1898681 ,
         2.15416328,   3.40499375,   5.49708857,   7.95136965,
         5.85235955,   5.86222079,   9.77838368,  15.19806273,
         8.57358533,   0.71286684,   6.221979  ,   9.73108583,
         5.57137567,  11.38030904,   4.43575264,   3.05816002,
         6.50952986,   7.19178934,   0.38124692,   2.0509039 ,
         2.30907108,   9.30243125,   0.92583366,   0.46490438,
         0.        ,   2.7298865 ,   5.18395125,   9.27092781,
         2.01911908,   4.20807279,   4.57227294,   2.28509945,
         2.39243017,   0.        ,   1.55980051,   6.54600645,
         4.29208639,   3.13601258,   7.21567809,   1.16212371,
         0.45908598,   4.65032505,   3.86904134,   3.65467406,
        16.72702305,   7.33881755,   3.08346939,   2.57825636,
         3.37441772,   4.04151899,   0.87748462,   5.09284899,
        18.67441428,   2.88186807,  12.58984021,   7.77750098,
         2.18452401,   3.43468713,   8.05774275,   4.41357429,
         4.76273736,   9.62297627,   2.96324768,   1.86346515,
         5.00565549,  15.27693792,   0.        ,   0.        ,
         4.39728926,   3.8240252 ,   9.8908682 ,  13.41289068,
         5.85193246,   2.90144287,   3.263377  ,   4.12540794,
         8.98808217,   5.38563839,   6.4490794 ,   2.90370509,
         1.86518382,   1.63160336,   4.74767438,   0.36438362,
         4.30433379,   3.2385466 ,   0.        ,   5.20317844,
         3.70807508,   2.9186669 ,  15.43881416,   1.4491818 ,
         8.7794237 ,   3.90865686,   4.51930634,   8.94974937,
         2.02559069,   6.72853885,   6.12368373,  51.33840761,
         6.32007313,  17.91391062,  53.55384992,   5.69897883,
         3.69852952,  61.36523322,   5.51562457,   3.95234065,
        27.15543633,   3.33737003,   3.45556221,   0.        ,
        14.77359881,  12.51132109,   7.00779101,   9.77651751,
         5.40663797,   5.25767798,   6.40051083,  14.68110728,
         8.9927571 ,   9.97152008,   4.42626071,   9.28919366,
         6.33733283,   3.50655394,   4.10050386,  21.88332534,
         3.9217619 ,   5.93894496,  15.03871553,  12.05674809,
         6.36095144,   9.78848437,   4.07968518,  12.41552772,
         5.60815921,   3.55824879,  12.22959923,  13.26470381,
         9.67060654,  26.88276255,  30.26337008,   3.74251937,
         4.03360229,   2.96432973,   0.        ,   3.81889807,
         5.65411924,   3.58767115,  45.87335145,  22.71042369,
         3.24655456,   0.        ,   4.16830997,   2.7215628 ,
         2.24463564,  10.71990138,   7.32590627,  12.24279422,
        16.23569705,   7.04770025,   3.57259354,   5.43023053,
         2.28659006,   2.02399453,   7.95010651,   3.47706802,
         0.        ,   2.46512838,  66.41817677, 102.97876521,
         1.36447979,   4.17601957,   4.3060125 ,   0.93268366,
         1.67909685,   1.42736685,   0.        ,   5.4718543 ,
        20.92903441,   4.08814802,   4.09585243,  15.43710369,
         2.56749614,   4.16848487,   7.97457698,  62.44385636,
         9.54467504,   4.18863688,   1.96317851,   1.83795154,
         2.19857331,   3.09935553,   4.56982155,   1.0483673 ,
         7.06450411,   5.83282502,  55.76948068,   2.81890887,
         6.26266169,   2.95589037,   0.        ,   0.90111334,
         5.94207079,  10.80663626,  17.36487541,  47.25451743,
         0.57882039,   2.29712708,   3.83180583,   0.        ,
         2.3180842 ,  16.98445495,   3.40855906,   6.00145094,
         2.45668375,   9.94020201,   7.79471368,   8.53157483,
         3.26476589,   4.83880746,   2.89200541,  19.63449061,
         7.24956264,  10.81858156,   3.80832356,  15.76891894,
         3.96568944,  56.94539906,   3.88314157,   2.14513793,
         1.18067634,   4.6349485 ,   7.54254342,   5.65665765,
         4.05189627,   4.49977726,   2.35147906,   2.48998921,
        29.42720358,  14.02898178,   3.45562878,   7.89797714,
         8.34109875,  42.21548634,   3.65692041,   5.41349101,
        11.67704557,   5.63088672,  39.0916965 ,   3.29355234,
         5.19217622,   2.6190311 ,   2.9382635 ,   2.09488067,
         0.        ,   6.94881344,  62.7784505 ,   2.26807535,
         3.1804299 ,  12.96908334,   7.9700369 ,   4.34419186,
         9.45276026,  24.32834787,   7.10061089,   7.33030217,
         1.83176982,  11.01200753,   3.63685033,   3.5520638 ,
         0.99551932,   0.        ,   5.8793512 ,   0.87200665,
         3.20347261,  10.64959198,   5.80441119,   8.33546884,
         4.97820434,  19.07899225,  18.669132  ,  15.26240716,
         2.82781695,   2.93441073,   9.89704596,  11.16025228,
         4.98641342,   3.53356819,  11.38407756,  19.62857872,
         5.5865271 ,   7.84753663,   5.72048469,   0.        ,
         3.04666139,   0.        ,   0.        ,   3.55002687,
         4.78479806,   4.02123973,   4.58297055,  14.154611  ,
        10.00180527,   2.75785163,  20.75441262,   0.30496891,
         5.95230279,   4.43704254,   3.61758936,  14.84932041,
         2.29568482,   5.40943061,   5.16602064,   0.83674543,
         2.99647071,   4.01051063,   4.42787165,   0.        ,
         3.52486448,  41.14037139,   4.90653838,   1.69146975,
         6.05327176,  17.7915937 ,   2.43780785,   3.88979503,
        14.03380249,  29.06094206,   8.8873244 ,   0.54833377,
         6.38932127,   1.01477375,   4.19349316,   6.7703966 ,
         3.78177338,   6.4934109 ,   0.        ,  18.06945864,
         1.29818877,   3.3030894 ,   1.89019145,   0.46906435,
         7.40408024,  38.02437126,  88.12060714,  10.20601921,
         9.17444938,   7.00714502,   3.21105252,   4.23636041,
         2.74370483,   7.67454255,   5.2130498 ,   7.26143201,
         0.        ,   3.89826194,   0.        ,   0.43780794,
         3.12060375,   2.62417172,   5.65029369,   5.0739109 ,
         4.3919491 ,  12.39264485,   3.35884027,   7.41999124,
         3.3845319 ,   4.0908909 ,   3.69080631,   6.4384544 ,
         1.11082393,   2.53388472,   2.23858789,   9.3383781 ,
         2.30190068,   0.92956227,  12.26709347,   9.37420714,
         2.73376192,  23.14900261,   0.61696765,   1.73548674,
         1.26657426,  25.62898371,   2.25365988,   4.56404537,
         1.88692715,   1.89683236,  16.87345932,  13.33341784,
         2.52907489,   4.41851656,   5.88383912,   1.        ,
        27.15032282,   5.09198   ,   7.66120274,   3.34597699,
         0.57536593,   0.        ,   4.78384315,   2.37865921,
         1.25989699,   0.        ,   3.45174087,   5.47601027,
         4.21579152,   0.44542288,   2.88429583,   2.47678435,
         7.00936097,   2.69288218,  14.52685091,   0.        ,
         0.        ,   6.6250636 ,  11.68507994,  10.24173938,
         5.73825405,   2.4855301 ,   5.07981325,   1.82435497,
         4.08354456,   1.91773353,   3.3792492 ,   9.88425629,
         0.        ,   2.29153203,   0.50921296,   0.2507455 ,
         9.97633612,   3.73386656,   5.04533993,   3.61714036,
        13.62059516,   6.7140589 ,  24.57771758,   4.38552455,
         2.64722529,   1.29978452,   1.68274529,   1.87835088,
        11.053779  ,   1.61296591,   2.6734955 ,   0.        ,
         7.95294845,   2.83817502,   0.        ,   2.85658089,
         0.        ,  29.26718105,   4.87353776,   0.        ,
         6.01071346,   2.69016456,  12.81580976,   3.21960884,
         1.67467615,   0.        ,   2.51263013,   7.66962701,
         2.36655668,   7.09296427,   0.        ,   4.56381008,
        18.01948852,   2.38096267,   8.9428325 ,   2.66987154,
         0.        ,   2.20824936,   9.2193313 ,  24.56992259,
         6.88191838,   7.92151402,   6.89977139,   8.79208439,
         3.61474713,   4.86502684,   7.38011164,   1.32952879,
         6.18521564,   5.38156727,   2.20750121,   2.78307502,
         2.53597985,   4.50169719,  30.12008151,   4.60560171,
         2.68004614,  16.02162815,   0.9611657 ,   0.32016065,
         6.40975491,   0.58116399,   2.66982351,  13.4969534 ,
        10.59969003,  12.35994442,   4.25594325,   8.03399629,
         2.59788786,   0.68764482,   3.12556669,   4.28992208,
         1.47733172,   4.31915762,  15.40147027,   5.08825721,
         5.87776592,   3.90248314,   2.9933962 ,  15.27497734,
         5.31203614,   3.82902635,   4.17848162,   9.14356554,
         4.84687609,   5.18733524,   5.25123419,   4.56388519,
         3.51852027,   0.40537892,  14.93423839,  46.02850466,
         2.58224226,   3.26906651,   5.66115313,   3.7570528 ,
         8.1877257 ,   9.98929349,   0.        ,   3.9983237 ,
         3.59183751,   8.69350408,   6.193515  ,   1.08078181,
         1.60426843,   0.43952352,   4.71173216,   3.54211608,
        10.11551488,   1.03560986,   5.95448342,   3.57596255,
         4.13326717,   3.2363813 ,  11.90572354,   3.8337551 ,
         5.22904551,   0.47333814,   3.31070315,   6.0760625 ,
        21.26404977,   1.74973788,   8.7823638 ,   3.37656029,
         3.53142576,   6.98998838,  15.86349026,   7.42009067,
         4.87185546,   0.69267926,   0.        ,   4.31020196,
        32.19542938,   4.22345164,   0.        ,   0.59325379,
         6.41378692,  17.50285676,   4.0160278 ,   3.49656767,
         8.81646981,  20.83547999,  11.38952237,  30.52950666,
         3.0326597 ,   8.55451698,   2.96241682,  16.26563856,
         9.84056747,  35.48932938,   4.38520686,   7.03915045,
         0.76193847,  12.98317192,   4.09755451,  14.49868012,
         3.7235918 ,   1.9129808 ,   2.62796842,   8.24640959,
         5.33755684,  51.12571264,   7.04394634,   5.38734215,
         9.46432649,  35.73028963,   3.01650623,  20.30851294,
         5.77503038,  24.29941299,   0.        ,   0.        ,
        18.73546973,   6.46582885,   6.76462274,   5.89894238,
        11.29264107,   3.62931024,   5.11781947,   7.03278638,
         2.11988797,   6.09146356,   2.47264877,   6.05050152,
         3.89132568,   2.9216431 ,  13.83967523,  10.81987668,
         0.        ,   3.4900175 ,   3.24653745,   9.63019632,
         4.1108458 ,   0.7230793 ,   0.        ,   5.01962178,
         0.        ,   4.86847231,   0.43508198,   4.66707395,
         3.10517371,   3.93097358,   2.23413505,   0.        ,
         0.        ,   2.06243754,  48.65819089,   3.86245373,
         0.4202078 ,   4.14007458,  13.58657401,   3.67086487,
         0.29817182,   3.56172397,   0.        ,   0.5063142 ,
         0.69366528,   2.66381104,   3.62912084,   3.04490363,
         0.33398065,   0.        ,  15.98052258,  11.44230108,
         8.30493705,   6.88372843,   2.9997062 ,  14.76739302,
         5.36882192,   8.63883183,  44.64494538,   6.18752385,
         6.23134077,   0.        ,   5.1165036 ,  28.19158729,
        10.47487401,  13.35135705,   4.74613589,   5.41060742,
        27.82919509,   3.81465455,   3.16040792,   4.08370984,
        18.82289085,   7.28696283,   1.40683513,   0.        ,
         0.94816871,   1.88288771,   6.02229507,  15.56475877,
         1.6196643 ,  12.35013503,   3.96829412,   3.04773656,
         2.54840202,   8.31064405,   4.07784988,   7.191646  ,
         2.25517736,   6.24166518,   0.        ,  13.68965084,
         2.70830854,   3.11025185,   3.53092611,   2.65594677,
         0.        ,   3.65112079,   0.        ,   4.22252982,
         4.98989227,   2.81609584,  15.67723197,   3.74004303,
         7.63846769,  29.11401579,   9.7539846 ,   7.97331523,
         3.69785742,   2.23981448,   7.32131785,   3.05149796,
         1.60030201,   8.78592908,   2.59104009,   4.12746236,
         4.72731542,   0.        ,   3.36264134,   2.05003816,
         7.62978479,   3.7182152 ,  17.37573735,   4.912349  ,
        27.9671714 ,  11.88448747,   6.8991618 ,   4.77626317,
        23.54114192,   2.33471693,   7.59436274,  10.34928285,
         3.27477612,   4.63708697,  16.59270378,   4.1499439 ,
         0.74568066,   1.28488782,  17.13269784,   0.        ])

In [72]:
# number of times each token appears across all SPAM messages
spam_token_count = nb.feature_count_[1, :]
spam_token_count

array([ 4.09705418,  3.01174689,  3.25113176,  2.07467781,  2.56477936,
        2.59625352,  7.90440729,  9.28381092,  2.27642246,  4.22306018,
        2.81134806,  2.13058597,  3.45226584,  4.70301592,  7.7477488 ,
        5.7488597 ,  3.337602  ,  8.07537499,  9.41257991,  9.10607985,
        5.51048768,  3.00354357,  8.21356426,  3.6665166 ,  5.92006528,
        2.07072364,  1.50821818,  3.89003729,  1.50737513,  2.2163558 ,
        2.6370755 ,  3.5039463 ,  1.52406548,  1.53802172,  1.87686297,
        2.11511878,  0.        ,  1.30488058,  1.30103813,  7.67533735,
        5.46056338,  2.07467781,  2.56209584,  4.50082487,  6.06878318,
        4.91630454,  3.96551476,  2.82782797,  1.63823391,  0.        ,
        0.        ,  0.        ,  0.        ,  4.22448396,  0.        ,
        1.086267  ,  3.18562342,  0.        ,  0.        ,  2.87460694,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.96097776,  1.51848008,  0.        ,  2.35294501,  6.32378804,
        0.        ,  1.83499511,  0.        ,  1.46006063,  0.81943569,
        0.        ,  0.        ,  1.58551999,  0.        ,  0.        ,
        4.0724949 ,  3.30219006,  0.90831419,  0.65905978,  4.61659338,
        2.16723261,  5.34308131,  9.08622362,  1.22145331,  0.        ,
        1.58256134,  2.14164389,  1.02992227,  0.61390518,  0.        ,
        0.        ,  0.55621969,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.36529181,  1.98111815,  0.        ,  0.62524229,  0.29013481,
        0.        ,  0.        ,  2.34759318,  0.        ,  4.53545087,
        1.53816413,  0.        ,  1.11961796,  0.        ,  0.        ,
        7.76860899,  0.        ,  0.        ,  0.75480574,  0.        ,
        0.25963525,  0.        ,  1.25446009,  2.40058695,  0.        ,
        0.        ,  0.        ,  0.93008297,  0.43641254,  0.        ,
        1.07777622,  2.79369274,  3.2757832 ,  0.36788326,  7.45241959,
        0.        ,  1.37538827,  1.6012331 ,  0.        ,  0.        ,
       13.13986258,  0.        ,  5.62368268,  0.        ,  2.97750538,
        2.90951087,  2.2219356 ,  8.52121111,  0.65237691,  1.2716798 ,
        0.        ,  0.        ,  0.        ,  0.        ,  2.44841728,
        0.        , 21.30040368,  0.50561202,  0.65936248,  4.12840505,
        6.43712469,  5.25269583,  6.37825463,  0.        ,  3.17639287,
        0.27815117,  1.40125677,  0.        ,  0.        ,  2.08249291,
        0.44775759,  0.4703814 ,  0.43931953,  3.25167265,  1.17143281,
        0.3356347 ,  3.00768676,  4.0057593 , 11.34121108,  0.29330588,
        0.        ,  1.30803016,  0.        ,  5.35998698,  0.        ,
        0.        ,  0.        ,  0.        ,  1.86646314,  2.44510488,
        3.36751634,  2.07467781,  3.29352868,  1.67840958,  2.49398994,
        2.25560816, 12.24743718,  0.        ,  0.53788776,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  1.99833757,
        5.10818681,  2.60341624,  2.68944068,  0.        ,  2.9901647 ,
        0.        ,  0.        ,  0.        ,  1.90419599,  4.40157791,
        0.        ,  0.        ,  1.11845189,  0.69144255,  0.        ,
        0.        ,  0.38221559,  0.        ,  0.        ,  2.38801781,
        0.        ,  0.        ,  2.8511202 ,  0.36488791,  1.83879949,
        0.        ,  0.        ,  0.71722108,  0.        ,  3.64378978,
        0.        ,  0.        ,  0.        ,  3.54860601,  3.23246782,
        0.79305027,  8.44002793,  1.26714582,  0.        ,  0.        ,
        0.        ,  0.87598327,  0.59827017,  0.        ,  0.        ,
        0.        ,  2.22992078,  0.        ,  0.        ,  2.69358311,
        0.        ,  0.        ,  0.36311345,  0.89244394,  4.06889461,
        1.81091084,  1.45541289,  0.8787697 ,  3.01909801,  2.76363623,
        1.88515041,  4.67731199,  0.        ,  1.10976135,  0.36121051,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        3.74837908,  1.75973759,  0.        ,  0.        ,  0.32288812,
        0.        ,  1.98018971,  2.08520269,  0.        ,  0.        ,
        0.        ,  0.        ,  0.55302282,  0.        ,  0.        ,
        0.        ,  0.82478104,  3.10512497,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  1.0100411 ,  1.3429416 ,
        0.        ,  0.        ,  0.89269324,  0.        ,  0.        ,
        1.54139691,  0.        , 32.37391835,  3.12165714,  2.73254492,
        0.37610142,  0.        ,  3.18937307,  0.80355085,  0.        ,
        0.        ,  1.98376702,  0.        ,  0.        ,  0.        ,
        2.32503205,  0.        ,  1.00019069,  0.        ,  2.55988746,
        4.43743236,  0.        ,  0.        ,  2.03138548,  0.        ,
        0.        ,  0.66167514,  0.73579674,  4.54967951,  0.65872375,
        2.26269142,  0.4199816 ,  0.36741258,  0.        ,  0.        ,
        0.        ,  0.84254505,  0.        ,  0.        ,  2.5209442 ,
        0.        ,  0.        ,  1.375134  ,  0.        ,  1.44220015,
        1.95854486,  0.        ,  0.        , 11.29629452,  0.        ,
        1.67180092,  0.        ,  1.71184322,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  2.63420988,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.26795532,
        0.36986988,  0.        ,  0.        ,  0.        ,  0.        ,
        0.79016755,  1.0509683 ,  0.71228657,  0.        ,  0.        ,
        0.95639819,  5.64596985,  0.        ,  0.97224388,  3.02790485,
        0.71455666,  0.        ,  0.        ,  1.88025781,  0.        ,
        0.        ,  6.97325846,  0.48473334,  1.06596182,  0.        ,
        2.36530598,  0.        ,  3.67779749,  0.84723364,  0.        ,
        1.54427481,  0.        ,  0.        ,  0.        ,  0.55017348,
        0.        ,  0.        ,  0.        ,  0.39734848,  0.        ,
        3.74837908,  0.        ,  0.2130193 ,  1.9534133 ,  2.88732694,
        3.45926231,  0.36321676,  2.57255989,  2.71149679,  1.11932684,
        2.35331457,  0.        ,  0.31352184,  0.        ,  0.        ,
        0.        ,  0.        ,  4.21270236,  0.        , 11.52881166,
        0.        ,  0.        ,  0.        ,  0.83562494,  1.12774403,
        0.        ,  0.        ,  1.18010209,  0.        ,  0.        ,
        3.87448546,  0.        ,  0.        ,  0.        ,  5.42525776,
        8.03891489,  0.        ,  0.        ,  0.        ,  0.        ,
        7.16132892,  0.37038078,  0.        ,  2.45730718,  0.41511993,
        0.60049121,  0.        ,  0.        ,  0.        ,  0.43641254,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  1.08595105,  0.        ,  0.        ,  0.69684867,
        0.        ,  2.62420657,  0.        ,  8.43776795,  2.5777111 ,
        0.45115831,  1.10987646,  4.67006632,  0.        ,  0.40755113,
        1.64500754,  1.98430764,  0.        ,  0.        ,  0.        ,
        0.95229846,  2.41694258,  0.        ,  0.37316915,  1.39358212,
        0.        ,  0.30418153,  1.44535799,  0.        ,  0.        ,
        0.40698882,  0.        ,  0.        ,  2.83261582,  0.        ,
        0.        ,  1.47722493,  1.89884375,  0.        ,  1.45659225,
        0.        ,  0.        ,  2.9366035 ,  0.        ,  0.        ,
        0.        ,  0.28067099,  0.        ,  0.        ,  1.63663708,
        2.3766148 ,  0.        ,  3.08782375,  0.        ,  0.26524294,
        0.        ,  0.        ,  0.        ,  1.74231031,  0.        ,
        8.59358383,  2.29320183,  0.36174281,  3.50235199,  0.33529944,
        6.8419668 ,  2.14530648,  0.74551721,  1.54565795,  0.98688972,
        0.35902075,  0.        ,  6.16012918, 21.58160316,  2.51095062,
        3.27065973,  0.        ,  0.        ,  0.        ,  0.        ,
        0.54408442,  0.33244359,  1.14159203,  0.        ,  2.26980069,
        0.60704081,  0.        ,  0.        ,  5.48946151,  1.09652327,
        0.        ,  0.        ,  4.00493751,  0.        ,  0.        ,
        0.        ,  2.64985011,  0.        ,  2.0681218 ,  0.36766317,
        6.41045804,  0.        , 13.99819982,  2.96359587,  0.        ,
        0.        ,  1.1655568 ,  0.        ,  1.80510557,  0.        ,
       11.72779784,  0.        ,  0.        ,  0.43092173,  0.25520072,
        2.8902464 ,  5.24887362,  2.22961843,  0.27331641,  5.87774982,
        2.48749481,  0.        ,  0.28655121,  0.73951498,  0.        ,
        0.        ,  0.54813287,  0.        ,  0.        ,  0.78822211,
        0.        ,  0.        ,  0.34466197,  4.60839297,  0.        ,
        4.10942094,  5.89530635,  0.        ,  3.04339394,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.27740949,  0.        ,  2.49776761,
        1.26460399,  0.        ,  0.31183726,  0.65101136,  1.89904186,
        0.33526936,  0.53357899,  0.32288812,  8.9488789 ,  3.0403634 ,
        0.98526605,  2.99231517,  0.40848768,  0.91886565,  0.        ,
        3.50127583,  1.02847086,  1.26800245,  0.        ,  0.        ,
        0.        ,  4.59579693,  3.1037417 ,  2.25246342,  1.92462391,
        0.        ,  0.63577696,  8.17464185,  3.41367521,  0.        ,
        3.5999164 ,  0.65166603,  3.99781724,  0.        ,  0.        ,
        0.94026304,  2.31943597,  0.        ,  0.81177338,  0.        ,
        3.87365085,  0.        ,  4.73260773, 19.24065631,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.81188996,
        0.80896193,  1.15495987,  2.01781638,  0.        ,  0.        ,
        3.33597067,  0.        ,  4.33139627,  2.65440127,  0.31307523,
        0.        ,  0.47895609,  0.        ,  2.1301807 ,  4.59752533,
        0.23160421,  0.        ,  7.09082764,  1.11112398,  0.98486539,
        0.        ,  0.        ,  1.03267543,  0.        ,  2.77581207,
       19.31113774,  0.        ,  3.19037451,  0.35566163,  3.15071236,
        0.56903322,  1.57090759,  7.8681677 ,  0.        ,  0.36059806,
        0.        ,  0.        ,  1.4993735 ,  2.52256968,  0.        ,
        0.        ,  0.63589121,  0.        ,  4.91755753,  0.        ,
        0.        ,  1.51719602,  0.2778859 ,  2.54148975,  2.68736262,
        0.58827032,  0.        ,  0.2568611 ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.67652638,  0.        ,
        3.03327083,  0.        ,  0.        ,  5.68053893,  0.31533863,
        0.61469469,  0.        , 10.71323313,  0.        ,  0.        ,
        2.74792486, 13.91792391,  5.72075446,  0.37565319,  3.77672132,
        4.32496697,  0.        ,  0.        ,  0.31006119,  2.2930559 ,
        2.24698571,  0.        ,  7.08933018,  0.        ,  0.        ,
        1.71140694,  0.61124557,  0.3814277 ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  6.92745978,
        0.        ,  0.66511341,  2.55808561,  0.3166967 ,  0.87240168,
        0.48432637,  0.30427347,  0.29201525,  0.        ,  2.53613082,
        2.83730907,  2.52256968,  0.        ,  0.68279735,  1.33051159,
        0.50121699,  1.44208843,  1.2001239 ,  4.17475617,  1.16870279,
        0.        , 23.09373359,  2.22815746,  0.        ,  0.85596894,
        0.        ,  0.        ,  0.4672557 ,  0.        ,  0.        ,
        2.59734841,  0.84348739,  0.        ,  0.        ,  1.32314137,
        0.        ,  0.        ,  1.23626169,  0.        ,  1.80615148,
        0.        ,  0.        ,  5.4046125 ,  6.06065164,  0.43034959,
        2.45576353,  0.        ,  1.98437341,  1.84534075,  0.        ,
       23.03559676,  4.02958593,  0.        ,  0.33543428,  3.48022143,
        0.        ,  0.        ,  0.        ,  0.9357692 ,  0.        ,
        0.29079741,  0.33727006,  0.80651186,  0.        ,  0.        ,
        3.10306933,  0.        ,  0.        ,  0.38315857,  0.        ,
        0.        ,  0.41392236,  0.        ,  0.59827017,  4.40382054,
        0.        ,  0.        ,  0.        ,  2.55117418,  4.61195482,
        0.        ,  0.        ,  1.40225259, 10.70484695,  5.22610009,
        0.43418752,  0.        ,  0.        ,  0.        ,  0.93914985,
        0.        ,  0.        ,  0.        ,  4.12929185,  0.77266812,
        0.        ,  0.65203137,  0.        ,  0.        ,  1.40338487,
        3.7809711 ,  5.55811004,  0.        ,  0.        ,  1.11561848,
       24.03375273,  2.33195142,  2.68920463,  0.        ,  2.52256968,
        0.        ,  3.4428612 ,  0.        ,  0.        ,  0.        ,
        2.14222275,  3.74837908,  4.95931725,  4.15604227, 18.60779118,
        0.        , 13.20379651,  0.        ,  2.22694648,  0.        ,
        2.15303077,  0.        ,  5.40705014,  3.48195716,  5.33307454,
        1.79887503,  0.        ,  0.        ,  4.38371221,  3.50748264,
        0.45647493,  5.13674083,  0.        ,  0.31718561,  0.        ,
        0.51727136,  0.        ,  3.05155276,  5.10995465,  0.32008569,
        0.43088936,  3.45394557,  0.        ,  0.21431679,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  8.44025039,  1.58650228,  1.66685947,
        5.76022613,  4.3116062 ,  3.34219351,  0.        ,  0.        ,
        0.        ,  0.28340424,  0.        ,  0.        ,  1.42587741,
        0.        ,  0.31670187,  0.        , 12.42094019,  0.        ,
        3.6000928 ,  0.4232675 ,  0.        ,  0.        ,  0.        ,
        3.75815714,  3.05217078,  0.        , 14.5912433 ,  0.        ,
        0.        ,  0.        ,  0.65175515,  5.93152182,  0.        ,
        0.54415941,  0.        ,  0.37123132,  0.        ,  0.        ,
        0.        ,  0.        ,  3.38453429,  0.        ,  0.33171583,
        0.        ,  0.        ,  2.1631832 ,  3.39392836,  1.58748072,
        2.79955406,  0.        ,  0.        ,  0.        ,  0.        ,
        1.65693902,  1.15036409,  0.        ,  2.72819588,  0.        ,
        0.33007423,  0.33038651,  0.        ,  0.35358249,  0.66453707,
        1.15127191,  3.05718392,  1.10779222,  0.        ,  1.6755781 ])

In [76]:
# create a DataFrame of tokens with their separate ham and spam counts
tokens = pd.DataFrame({'token':X_train_tokens, 'ham':ham_token_count, 'spam':spam_token_count}).set_index('token')
tokens.sample(5,random_state=3)

              ham      spam
token
pay     16.873459  1.268002
shirt   15.401470  0.381428
urgent   0.000000  3.507483
credit   1.225454  2.445105
neva     4.193493  0.000000

In [77]:
# Naive Bayes counts the number of observations in each class
nb.class_count_

array([3617.,  562.])

In [81]:
# add 1 to ham and spam counts to avoid mathematical errors like dividing by zero.
tokens['ham'] = tokens.ham + 1
tokens['spam'] = tokens.spam + 1
tokens.sample(5, random_state=3)

             ham      spam  spam_ratio
token
pay     1.004942  1.004036    0.816671
shirt   1.004535  1.002458    0.542073
urgent  1.000276  1.008020   29.009902
credit  1.000615  1.006130    9.963136
neva    1.001436  1.001779    1.239232

In [82]:
# convert the ham and spam counts into frequencies
tokens['ham'] = tokens.ham / nb.class_count_[0]
tokens['spam'] = tokens.spam / nb.class_count_[1]
tokens.sample(5, random_state=3)

             ham      spam  spam_ratio
token
pay     0.000278  0.001787    0.816671
shirt   0.000278  0.001784    0.542073
urgent  0.000277  0.001794   29.009902
credit  0.000277  0.001790    9.963136
neva    0.000277  0.001783    1.239232

In [83]:
# calculate the ratio of spam-to-ham for each token
tokens['spam_ratio'] = tokens.spam / tokens.ham
tokens.sample(5, random_state=3)

             ham      spam  spam_ratio
token
pay     0.000278  0.001787    6.430141
shirt   0.000278  0.001784    6.422639
urgent  0.000277  0.001794    6.485769
credit  0.000277  0.001790    6.471414
neva    0.000277  0.001783    6.438151

In [84]:
# examine the DataFrame sorted by spam_ratio
# note: use sort() instead of sort_values() for pandas 0.16.2 and earlier
tokens.sort_values('spam_ratio', ascending=False)

                   ham      spam  spam_ratio
token
forgot        0.000278  0.001885    6.787591
tonite        0.000277  0.001859    6.713140
sms           0.000277  0.001856    6.691298
cleaning      0.000277  0.001850    6.689475
mobile        0.000277  0.001851    6.687063
subscription  0.000278  0.001855    6.677039
poly          0.000277  0.001843    6.665893
reach         0.000277  0.001844    6.652078
wish          0.000277  0.001829    6.612664
sending       0.000277  0.001827    6.603201
type          0.000277  0.001824    6.596013
change        0.000277  0.001824    6.586589
went          0.000277  0.001822    6.583713
dad           0.000277  0.001821    6.578505
network       0.000277  0.001820    6.578036
gym           0.000277  0.001818    6.574941
natural       0.000278  0.001827    6.573548
txt           0.000280  0.001841    6.570285
convey        0.000277  0.001818    6.568401
thinking      0.000277  0.001816    6.568169
200           0.000277  0.001812    6.552265
100           0.000277  0.001812    6.551900
2000          0.000277  0.001811    6.549866
bb            0.000277  0.001811    6.549638
2nd           0.000277  0.001809    6.539647
losing        0.000277  0.001809    6.538338
dude          0.000277  0.001809    6.538283
place         0.000277  0.001808    6.538162
1st           0.000277  0.001808    6.538065
let           0.000277  0.001808    6.536020
...                ...       ...         ...
away          0.000278  0.001783    6.401615
really        0.000279  0.001784    6.400353
won           0.000279  0.001784    6.400339
vodafone      0.000279  0.001783    6.398211
drive         0.000279  0.001783    6.397541
nah           0.000280  0.001789    6.396555
wake          0.000279  0.001783    6.396412
xxx           0.000279  0.001783    6.396170
direct        0.000279  0.001785    6.393876
ltdecimalgt   0.000279  0.001783    6.393610
makes         0.000280  0.001787    6.393084
talk          0.000279  0.001785    6.392145
sure          0.000279  0.001783    6.391678
lect          0.000281  0.001795    6.391450
nokia         0.000279  0.001783    6.381822
gr8           0.000281  0.001791    6.380037
drop          0.000281  0.001794    6.378211
lor           0.000281  0.001791    6.375313
sing          0.000280  0.001785    6.374504
lunch         0.000280  0.001783    6.371272
dare          0.000280  0.001783    6.371092
hr            0.000280  0.001784    6.370391
good          0.000280  0.001785    6.364942
life          0.000280  0.001783    6.362512
grl           0.000281  0.001787    6.353592
max10mins     0.000281  0.001783    6.335678
comes         0.000282  0.001783    6.335350
iq            0.000282  0.001783    6.331814
noon          0.000283  0.001785    6.300620
isnt          0.000284  0.001789    6.288974

[1000 rows x 3 columns]

In [85]:
# look up the spam_ratio for a given token
tokens.loc['prize', 'spam_ratio']

6.475553514607247

In [89]:
# look up the spam_ratio for a given token
tokens.loc['doing', 'spam_ratio']

6.422157706264464